# Generated by Django 6.0 on 2026-05-03 23:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Нэр')),
                ('icon', models.CharField(blank=True, max_length=100, verbose_name='Icon')),
            ],
            options={
                'verbose_name': 'Нэмэлт үйлчилгээ',
                'verbose_name_plural': 'Нэмэлт үйлчилгээнүүд',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Нэр')),
                ('name_en', models.CharField(blank=True, max_length=255, verbose_name='Англи нэр')),
                ('is_airport', models.BooleanField(default=False, verbose_name='Нисэх буудал эсэх')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй эсэх')),
            ],
            options={
                'verbose_name': 'Байршил',
                'verbose_name_plural': 'Байршлууд',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Нэр')),
                ('category', models.CharField(choices=[('economy', 'Эдийн засгийн'), ('comfort', 'Тав тухтай'), ('luxury', 'Тансаг'), ('minibus', 'Микро автобус')], default='economy', max_length=20, verbose_name='Төрөл')),
                ('price', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Үнэ (₮)')),
                ('passenger_capacity', models.PositiveIntegerField(default=3, verbose_name='Хэдэн хүн суух')),
                ('luggage_capacity', models.PositiveIntegerField(default=2, verbose_name='Ачааны тоо')),
                ('image', models.ImageField(blank=True, null=True, upload_to='vehicles/', verbose_name='Зураг')),
                ('is_active', models.BooleanField(default=True, verbose_name='Идэвхтэй эсэх')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('amenities', models.ManyToManyField(blank=True, to='taxi.amenity', verbose_name='Нэмэлт үйлчилгээ')),
            ],
            options={
                'verbose_name': 'Тээврийн хэрэгсэл',
                'verbose_name_plural': 'Тээврийн хэрэгслүүд',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_count', models.PositiveIntegerField(default=1, verbose_name='Зорчигчийн тоо')),
                ('luggage_count', models.PositiveIntegerField(default=0, verbose_name='Ачааны тоо')),
                ('pickup_datetime', models.DateTimeField(verbose_name='Авах цаг')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Нийт үнэ (₮)')),
                ('status', models.CharField(choices=[('pending', 'Хүлээгдэж байна'), ('confirmed', 'Баталгаажсан'), ('in_progress', 'Явж байна'), ('completed', 'Дууссан'), ('cancelled', 'Цуцлагдсан')], default='pending', max_length=20, verbose_name='Төлөв')),
                ('contact_name', models.CharField(max_length=255, verbose_name='Нэр')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Утас')),
                ('notes', models.TextField(blank=True, verbose_name='Тэмдэглэл')),
                ('can_cancel_before', models.DateTimeField(blank=True, null=True, verbose_name='Цуцлах хугацаа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxi_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Хэрэглэгч')),
                ('from_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxi_from', to='taxi.location', verbose_name='Хаанаас')),
                ('to_location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxi_to', to='taxi.location', verbose_name='Хаашаа')),
                ('vehicle', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxi_bookings', to='taxi.vehicle', verbose_name='Тээврийн хэрэгсэл')),
            ],
            options={
                'verbose_name': 'Захиалга',
                'verbose_name_plural': 'Захиалгууд',
                'ordering': ['-created_at'],
            },
        ),
    ]
