# Generated by Django 6.0 on 2026-05-09 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='from_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxi_from', to='taxi.location', verbose_name='Хаанаас'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='to_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxi_to', to='taxi.location', verbose_name='Хаашаа'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Нийт үнэ (₮)'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taxi_bookings', to='taxi.vehicle', verbose_name='Тээврийн хэрэгсэл'),
        ),
    ]
