# Generated by Django 6.0 on 2026-04-09 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TourPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('duration', models.IntegerField()),
                ('max_people', models.IntegerField()),
                ('guide', models.CharField(max_length=100)),
                ('accommodation', models.CharField(max_length=200)),
                ('transportation', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('included', models.TextField()),
                ('price', models.FloatField()),
                ('image', models.URLField()),
            ],
        ),
    ]
