# Generated by Django 6.0 on 2026-04-09 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='accommodation',
            field=models.CharField(max_length=200, verbose_name='Буудал'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='description',
            field=models.TextField(verbose_name='Дэлгэрэнгүй мэдээлэл'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='duration',
            field=models.IntegerField(verbose_name='Хугацаа (өдөр)'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='guide',
            field=models.CharField(max_length=100, verbose_name='Хөтөч'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='image',
            field=models.URLField(verbose_name='Зураг URL'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='included',
            field=models.TextField(verbose_name='Багцад багтсан зүйлс'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='location',
            field=models.CharField(max_length=200, verbose_name='Байршил'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='max_people',
            field=models.IntegerField(verbose_name='Хүний дээд тоо'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Аяллын нэр'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='price',
            field=models.FloatField(verbose_name='Үнэ'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='start_date',
            field=models.DateField(verbose_name='Эхлэх огноо'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='transportation',
            field=models.CharField(max_length=200, verbose_name='Тээвэр'),
        ),
    ]
