# Generated by Django 6.0 on 2026-04-09 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_tourpackage_accommodation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourpackage',
            name='image',
            field=models.ImageField(upload_to='tour_images/', verbose_name='Зураг'),
        ),
    ]
