# Generated by Django 6.0 on 2026-04-13 21:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0003_alter_tourpackage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourpackage',
            name='start_date',
        ),
        migrations.AddField(
            model_name='tourpackage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Үнэ'),
        ),
    ]
