# Generated by Django 6.0 on 2026-04-13 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_remove_tourpackage_start_date_tourpackage_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Суурь үнэ'),
        ),
    ]
