# Generated by Django 6.0 on 2026-04-13 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_tourpackage_updated_at_alter_tourpackage_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='TourSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Эхлэх огноо')),
                ('end_date', models.DateField(verbose_name='Дуусах огноо')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='trips.tourpackage', verbose_name='Аялал')),
            ],
        ),
    ]
