# Generated by Django 6.0 on 2026-04-13 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0006_tourschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourschedule',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10, verbose_name='Нэг хүний үнэ'),
            preserve_default=False,
        ),
    ]
