# Generated by Django 6.0 on 2026-04-14 05:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0007_tourschedule_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tourschedule',
            options={'ordering': ['start_date'], 'verbose_name': 'Аяллын хуваарь', 'verbose_name_plural': 'Аяллын хуваарь'},
        ),
        migrations.AddField(
            model_name='tourschedule',
            name='available_seats',
            field=models.PositiveIntegerField(default=0, verbose_name='Үлдсэн суудал'),
        ),
        migrations.AddField(
            model_name='tourschedule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='duration',
            field=models.PositiveIntegerField(verbose_name='Хугацаа (өдөр)'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='max_people',
            field=models.PositiveIntegerField(verbose_name='Хүний дээд тоо'),
        ),
    ]
