# Generated by Django 6.0 on 2026-04-14 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0008_alter_tourschedule_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Нэр')),
                ('last_name', models.CharField(max_length=100, verbose_name='Овог')),
                ('email', models.EmailField(max_length=254, verbose_name='Имэйл')),
                ('phone', models.CharField(max_length=20, verbose_name='Утас')),
                ('people', models.PositiveIntegerField(verbose_name='Хүний тоо')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Нийт үнэ')),
                ('status', models.CharField(choices=[('pending', 'Хүлээгдэж буй'), ('confirmed', 'Баталгаажсан'), ('cancelled', 'Цуцлагдсан')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='trips.tourschedule')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='trips.tourpackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL, verbose_name='Хэрэглэгч')),
            ],
        ),
    ]
