# Generated by Django 6.0 on 2026-04-14 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0009_booking'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['-created_at'], 'verbose_name': 'Захиалга', 'verbose_name_plural': 'Захиалгууд'},
        ),
        migrations.AlterModelOptions(
            name='tourpackage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Аялал', 'verbose_name_plural': 'Аяллууд'},
        ),
        migrations.AlterField(
            model_name='booking',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='trips.tourschedule', verbose_name='Хуваарь'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='trips.tourpackage', verbose_name='Аялал'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tour_images/', verbose_name='Зураг'),
        ),
    ]
