# Generated by Django 6.0 on 2026-05-09 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_remove_flight_flights_fli_origin__52e71a_idx_and_more'),
        ('trips', '0010_alter_booking_options_alter_tourpackage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Төрсөн огноо'),
        ),
        migrations.AddField(
            model_name='booking',
            name='flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='flights.flight', verbose_name='Нислэг'),
        ),
        migrations.AddField(
            model_name='booking',
            name='gender',
            field=models.CharField(blank=True, max_length=20, verbose_name='Хүйс'),
        ),
        migrations.AddField(
            model_name='booking',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, verbose_name='Иргэншил'),
        ),
        migrations.AddField(
            model_name='booking',
            name='passport_expire_date',
            field=models.DateField(blank=True, null=True, verbose_name='Паспорт дуусах хугацаа'),
        ),
        migrations.AddField(
            model_name='booking',
            name='passport_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Паспорт дугаар'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Имэйл'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='people',
            field=models.PositiveIntegerField(default=1, verbose_name='Хүний тоо'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Утас'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='trips.tourschedule', verbose_name='Хуваарь'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Нийт үнэ'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='trips.tourpackage', verbose_name='Аялал'),
        ),
    ]
