# Generated by Django 6.0 on 2026-05-09 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0002_alter_booking_from_location_and_more'),
        ('trips', '0011_booking_birth_date_booking_flight_booking_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='apartment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Хороолол / Байр'),
        ),
        migrations.AddField(
            model_name='booking',
            name='detail_address',
            field=models.TextField(blank=True, verbose_name='Дэлгэрэнгүй хаяг'),
        ),
        migrations.AddField(
            model_name='booking',
            name='district',
            field=models.CharField(blank=True, max_length=255, verbose_name='Дүүрэг'),
        ),
        migrations.AddField(
            model_name='booking',
            name='flight_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Нислэгийн дугаар'),
        ),
        migrations.AddField(
            model_name='booking',
            name='khoroo',
            field=models.CharField(blank=True, max_length=255, verbose_name='Хороо'),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_date',
            field=models.DateField(blank=True, null=True, verbose_name='Тосох огноо'),
        ),
        migrations.AddField(
            model_name='booking',
            name='pickup_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Тосох цаг'),
        ),
        migrations.AddField(
            model_name='booking',
            name='street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Гудамж'),
        ),
        migrations.AddField(
            model_name='booking',
            name='taxi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='taxi.vehicle', verbose_name='Такси'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Хүлээгдэж буй'), ('confirmed', 'Баталгаажсан'), ('cancelled', 'Цуцлагдсан')], default='pending', max_length=20, verbose_name='Төлөв'),
        ),
    ]
