# Generated by Django 6.0 on 2026-05-03 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='IATA код')),
                ('name', models.CharField(max_length=200, verbose_name='Нэр')),
                ('name_mn', models.CharField(blank=True, max_length=200, verbose_name='Монгол нэр')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='airlines/', verbose_name='Лого')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Авиа компани',
                'verbose_name_plural': 'Авиа компаниуд',
            },
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='IATA код')),
                ('name', models.CharField(max_length=200, verbose_name='Нэр')),
                ('name_mn', models.CharField(blank=True, max_length=200, verbose_name='Монгол нэр')),
                ('city', models.CharField(max_length=100, verbose_name='Хот')),
                ('city_mn', models.CharField(blank=True, max_length=100, verbose_name='Хот (монгол)')),
                ('country', models.CharField(max_length=100, verbose_name='Улс')),
                ('country_mn', models.CharField(blank=True, max_length=100, verbose_name='Улс (монгол)')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Нисэх буудал',
                'verbose_name_plural': 'Нисэх буудлууд',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Эхлэх үнэ')),
                ('date_range_start', models.DateField(verbose_name='Явах огноо')),
                ('date_range_end', models.DateField(verbose_name='Ирэх огноо')),
                ('image', models.ImageField(blank=True, null=True, upload_to='featured/', verbose_name='Зураг')),
                ('image_url', models.URLField(blank=True, verbose_name='Зургийн URL')),
                ('badge', models.CharField(default='2 талдаа', max_length=20, verbose_name='Тэмдэглэгээ')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Эрэмбэ')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_destinations', to='flights.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_origins', to='flights.airport')),
            ],
            options={
                'verbose_name': 'Онцлох нислэг',
                'verbose_name_plural': 'Онцлох нислэгүүд',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight_number', models.CharField(max_length=50, verbose_name='Нислэгийн дугаар')),
                ('departure_date', models.DateTimeField(verbose_name='Явах огноо цаг')),
                ('arrival_date', models.DateTimeField(verbose_name='Ирэх огноо цаг')),
                ('return_date', models.DateField(blank=True, help_text='Зөвхөн 2 талдаа захиалгад хэрэглэнэ', null=True, verbose_name='Буцах огноо')),
                ('total_seats', models.PositiveIntegerField(default=0, verbose_name='Нийт суудал')),
                ('available_seats', models.PositiveIntegerField(default=0, verbose_name='Сул суудал')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Үнэ (₮)')),
                ('flight_class', models.CharField(choices=[('economy', 'Энгийн'), ('business', 'Бизнес'), ('first', '1-р анги')], default='economy', max_length=10, verbose_name='Нислэгийн анги')),
                ('status', models.CharField(choices=[('scheduled', 'Хуваарьт'), ('delayed', 'Хойшлогдсон'), ('cancelled', 'Цуцлагдсан'), ('departed', 'Явсан'), ('arrived', 'Ирсэн')], default='scheduled', max_length=15, verbose_name='Төлөв')),
                ('is_direct', models.BooleanField(default=True, verbose_name='Шууд нислэг')),
                ('stops', models.PositiveSmallIntegerField(default=0, verbose_name='Зогсолтын тоо')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('airline', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='flights', to='flights.airline', verbose_name='Авиа компани')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrivals', to='flights.airport', verbose_name='Очих буудал')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='departures', to='flights.airport', verbose_name='Гарах буудал')),
            ],
            options={
                'verbose_name': 'Нислэг',
                'verbose_name_plural': 'Нислэгүүд',
                'ordering': ['departure_date'],
                'indexes': [models.Index(fields=['origin', 'destination', 'departure_date'], name='flights_fli_origin__52e71a_idx'), models.Index(fields=['departure_date'], name='flights_fli_departu_60abbf_idx'), models.Index(fields=['status'], name='flights_fli_status_e6e528_idx')],
            },
        ),
    ]
