# Generated by Django 6.0 on 2026-05-09 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='flight',
            name='flights_fli_origin__52e71a_idx',
        ),
        migrations.RemoveIndex(
            model_name='flight',
            name='flights_fli_departu_60abbf_idx',
        ),
        migrations.RemoveIndex(
            model_name='flight',
            name='flights_fli_status_e6e528_idx',
        ),
        migrations.AddField(
            model_name='featuredflight',
            name='arrival_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Ирэх цаг'),
        ),
        migrations.AddField(
            model_name='featuredflight',
            name='departure_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Явах цаг'),
        ),
        migrations.AlterField(
            model_name='featuredflight',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_destinations', to='flights.airport', verbose_name='Очих буудал'),
        ),
        migrations.AlterField(
            model_name='featuredflight',
            name='origin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_origins', to='flights.airport', verbose_name='Гарах буудал'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='return_date',
            field=models.DateField(blank=True, null=True, verbose_name='Буцах огноо'),
        ),
    ]
